# Generated by Django 4.2.5 on 2023-09-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_like_alter_feedcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
