# Generated by Django 4.2.5 on 2023-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feed_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
