# Generated by Django 4.2.5 on 2023-09-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_like_alter_feedcomment_content_and_more'),
        ('user', '0002_usermodel_follow_alter_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='liked_feed',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed'),
        ),
    ]
