# Generated by Django 4.2.5 on 2023-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_like_alter_feedcomment_content_and_more'),
        ('user', '0003_usermodel_liked_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='liked_feed',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='liked_feed',
            field=models.ManyToManyField(default=None, null=True, to='feed.feed'),
        ),
    ]
